server:
  port: ${PORT:8080}
  forward-headers-strategy: native

springdoc:
  swagger-ui:
    enabled: true
    configUrl: ${SPRINGDOC_PATH:}/v3/api-docs/swagger-config
    url: ${SPRINGDOC_PATH:}/v3/api-docs
  path-provider: ${SPRINGDOC_PATH:}

spring:
  application:
    name: boardgame-guide-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.redisson.spring.starter.RedissonAutoConfigurationV2
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  threads:
    virtual:
      enabled: true



jwt:
  secret: ThisIsSecretKey


sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${ENVIRONMENT:dev}
  connection-timeout-millis: 10000
  read-timeout-millis: 10000
  max-depth: 10
  max-breadcrumbs: 30
  max-cache-items: 100
  sample-rate: 0.1
  tags:
    project: boardgame-guide-api
    service: boardgame-guide-gateway
  send-default-pii: true
  logging.enabled: true
  logging.minimum-event-level: warn
  logging.minimum-breadcrumb-level: debug


management:
  endpoint:
    health:
      show-details: always
